spring:
  data:
    mongodb:
      uri: mongodb+srv://harry:1234@cluster0.s0c5boz.mongodb.net/
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  port: 8080
  servlet:
    context-path: /journal