spring:
  redis:

    host: redis-14289.c273.us-east-1-2.ec2.redns.redis-cloud.com:14289
    port: 14289
    password: gcplV42Gic2BTpnGBa0096jVZlTZT3vY
  data:
    mongodb:
      uri: mongodb+srv://harry:1234@cluster0.s0c5boz.mongodb.net/
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: email@email.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
  servlet:
    context-path: /journal